services:
  rabbit:
    image: rabbitmq:4-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service
  configserver:
   image: "MaciejGrzelec/configserver"
   container_name: configserver-ms
   ports:
     - "8071:8071"
   depends_on:
     rabbit:
       condition: service_healthy
   healthcheck:
     test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
     interval: 10s
     timeout: 5s
     retries: 10
     start_period: 10s
   extends:
     file: common-config.yml
     service: microservice-base-config

  apigateway:
    image: "MaciejGrzelec/apigateway:s6"
    container_name: apigateway-ms
    ports:
      - "8080:8080"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "apigateway"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  appointment:
    image: "MaciejGrzelec/appointment:s6"
    container_name: appointment-ms
    ports:
      - "8081:8081"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "appointment"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  clinic:
    image: "MaciejGrzelec/clinic:s6"
    container_name: clinic-ms
    ports:
      - "8082:8082"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "clinic"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  notification:
    image: "MaciejGrzelec/notification:s6"
    container_name: notification-ms
    ports:
      - "8084:8084"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "notification"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  patient:
    image: "MaciejGrzelec/patient:s6"
    container_name: patient-ms
    ports:
      - "8085:8085"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "patient"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  payment:
    image: "MaciejGrzelec/payment:s6"
    container_name: payment-ms
    ports:
      - "8086:8086"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "payment"
    extends:
      file: common-config.yml
      service: microservice-configserver-config