server:
  port: 8081

spring:
  application:
    name: "appointment"
  profiles:
    active: "prod"
  config:
      import: "optional:configserver:http://localhost:8071/"
  datasource:
    url: jdbc:postgresql://localhost:5434/clinic_db
    username: ${DB_USERNAME:clinicflow}
    password: ${DB_PASSWORD:clinicflow}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "appointment"
    description: "Clinic flow application"
    version: "1.0.0"